<?php
/**
 * @var Pointeger\Core\Block\AddComment $block ;
 */
?>
<form method="post" action="<?= $block->getAddCommentUrl() ?>">
    <fieldset>
        <div>
            <label for="customer_id"><?= __("customer_id") ?></label>
            <input type="number" name="customer_id" id="customer_id"/>
        </div>
        <div>
            <label for="name"><?= __("name") ?>
                <input type="text" name="name" id="name"/>
        </div>
        <div>
            <label for="comment"><?= __("comment") ?>
                <input type="text" name="comment" id="comment"/>
        </div>
        <input type="submit" value="<?= __("Add Comment") ?>"/>
    </fieldset>
</form>
