<?php
/**
 * @var Pointeger\Core\Block\CommentList $block ;
 */

$commentCollection = $block->getCustomerComment();
$size = $commentCollection->getSize();
$items = $commentCollection->getItems();
?>

<div class="table-container">
    <?php if (!$size) { ?>
        <h3>Opps You Have No Comments <i><u><a href="<?= $block->getUrl("core/comment/form") ?>">Add New
                        Comments</a></u></i></h3>
    <?php } else { ?>
        <table border="2px" class="table">
            <thead>
            <tr>
                <th>Entity Id</th>
                <th>Name</th>
                <th>Comment</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($items as $comment): ?>
                <tr class="customer-data<?= $comment->getEntityId() ?> " id="hello">
                    <td><?= $comment->getEntityId(); ?></td>
                    <td><?= $comment->getName(); ?></td>
                    <td><?= $comment->getComment(); ?></td>
                    <td>
                        <button data-name="test" data-id="<?= $comment->getEntityId() ?>" class="button">Delete</button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php } ?>

</div>
<script>
    require(["jquery", "mage/url"], function ($, url) {
        $(".button").click(function (e) {
            $.ajax({
                url: "<?= $block->getUrl("core/comment/ajaxdelete")?>",
                type: "POST",
                data: {id: e.target.dataset.id},
                error: function (error) {
                    console.log(error)
                },
                success: function () {
                    let getFormUrl = url.build("core/comment/form");
                    $(".customer-data" + e.target.dataset.id).remove();
                    if (!$("#hello").length) {
                        $(".table").remove();
                        $(".table-container").html(`<h3>Opps you have no comments <i><u><a href="${getFormUrl}">add new
                        comments here</a></u></i></h3>`);
                    }
                }
            })
        })
    });
</script>
