<?php
/**
 * @var Pointeger\Core\Block\CommentList $block ;
 */
?>

<div>
    <table border="2px">
        <thead>
        <tr>
            <th>Entity Id</th>
            <th>Name</th>
            <th>Comment</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getCustomerComment() as $comment): ?>
            <tr>
                <td><?= $comment->getEntityId(); ?></td>
                <td><?= $comment->getName(); ?></td>
                <td><?= $comment->getComment(); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>

    </table>
</div>
